name: Stephanie Kopf
favicon: null
layout_spectrum: 0.89297
typography_spectrum: 0.78679
title: Stephanie Kopf Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5dad2'
    - '#cab2ae'
    - '#7f7b71'
    - '#1f1514'
    - '#314150'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
